// Generated by tools/chapters/build.py.
ILY.data.stories.chapter2 = {
  "id": "chapter2",
  "title": "第二章 · 约定与夕阳",
  "start": "ch2_s01",
  "nodes": {
    "ch2_s01": {
      "type": "monologue",
      "text": "苏醒 —— “贫血”的谎言与迟到的道歉",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "checkpoint": true,
      "next": "ch2_001"
    },
    "ch2_001": {
      "type": "monologue",
      "text": "基生正在房间外收拾昨夜留下的狼藉。水族馆的那场争吵、以及“爱理”毫无征兆地倒下，还压在他的心口上。他一夜没怎么合眼，只能用忙碌来驱散不安。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "next": "ch2_002"
    },
    "ch2_002": {
      "type": "monologue",
      "text": "就在这时——房间的方向，传来一声短促的惊叫。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "next": "ch2_003"
    },
    "ch2_003": {
      "type": "dialogue",
      "text": "啊！",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "portrait": "portrait-airi",
      "next": "ch2_004"
    },
    "ch2_004": {
      "type": "monologue",
      "text": "基生的手一抖，水杯差点脱手。他几乎是撞开房门冲了进去。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "next": "ch2_005"
    },
    "ch2_005": {
      "type": "dialogue",
      "text": "爱理——！？",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "next": "ch2_006"
    },
    "ch2_006": {
      "type": "monologue",
      "text": "推开门，他看见爱理已经醒来，正坐在床上，一只手按着额头。基生原本紧绷到发疼的神情，顿时松了下来——可额头上那层冷汗，仍出卖了他的担忧。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "next": "ch2_007"
    },
    "ch2_007": {
      "type": "dialogue",
      "text": "太好了……你醒了啊……",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "next": "ch2_008"
    },
    "ch2_008": {
      "type": "dialogue",
      "text": "没事儿吧？身体没问题了吗？",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "next": "ch2_009"
    },
    "ch2_009": {
      "type": "monologue",
      "text": "爱理似乎还没有完全恢复。面对基生的询问，她稍微停顿了一下，随后故作轻松地回答。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "next": "ch2_010"
    },
    "ch2_010": {
      "type": "dialogue",
      "text": "嗯……嗯嗯！可能是有点……贫血的样子。",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "portrait": "portrait-airi",
      "next": "ch2_011"
    },
    "ch2_011": {
      "type": "monologue",
      "text": "她说着，笑了笑，可那笑容并没有落到眼底。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "next": "ch2_012"
    },
    "ch2_012": {
      "type": "dialogue",
      "text": "贫血吗……",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "next": "ch2_013"
    },
    "ch2_013": {
      "type": "dialogue",
      "text": "你别勉强，还是躺着比较好吧……",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "next": "ch2_014"
    },
    "ch2_014": {
      "type": "monologue",
      "text": "基生走近床边，认真劝她继续休息。可当他伸手时，爱理却像是被烫到一般，微微向后缩了一下。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "next": "ch2_015"
    },
    "ch2_015": {
      "type": "monologue",
      "text": "爱理坐在床沿，双手拘谨地并拢在膝前。她低着头，头发遮住了双眼，显得十分紧张。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "next": "ch2_016"
    },
    "ch2_016": {
      "type": "dialogue",
      "text": "没问题，没问题！",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "portrait": "portrait-airi",
      "next": "ch2_017"
    },
    "ch2_017": {
      "type": "dialogue",
      "text": "比起这个，那个……我……",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "portrait": "portrait-airi",
      "next": "ch2_018"
    },
    "ch2_018": {
      "type": "monologue",
      "text": "爱理的脸上带着细微的汗珠。她张了张嘴，像是要说什么，却又把话咽了回去。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "next": "ch2_019"
    },
    "ch2_019": {
      "type": "dialogue",
      "text": "我……",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "portrait": "portrait-airi",
      "next": "ch2_020"
    },
    "ch2_020": {
      "type": "monologue",
      "text": "基生看着她欲言又止的样子，有些疑惑。随即，昨日在水族馆的画面涌了上来——他说完那些气话后，“爱理”便在他面前昏倒。积攒了一整夜的愧疚，终于在此刻决堤。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "next": "ch2_021"
    },
    "ch2_021": {
      "type": "dialogue",
      "text": "爱理，",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "next": "ch2_022"
    },
    "ch2_022": {
      "type": "monologue",
      "text": "爱理还没有说完那句欲言又止的话，基生便走上前，一把将她拥入怀中。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "cg": "ch2-hug",
      "backgroundFit": "contain",
      "next": "ch2_023"
    },
    "ch2_023": {
      "type": "monologue",
      "text": "这个拥抱来得十分突然。爱理睁大双眼，身体僵在原地，显然没有预料到基生会这样回应。基生低下头，将脸埋在她的肩旁，双臂紧紧环住她。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "cg": "ch2-hug",
      "backgroundFit": "contain",
      "next": "ch2_024"
    },
    "ch2_024": {
      "type": "dialogue",
      "text": "对不起……",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "cg": "ch2-hug-close",
      "backgroundFit": "contain",
      "next": "ch2_025"
    },
    "ch2_025": {
      "type": "monologue",
      "text": "“爱理”一脸震惊地感受着这个拥抱，睫毛轻轻颤动。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "cg": "ch2-hug-close",
      "backgroundFit": "contain",
      "next": "ch2_026"
    },
    "ch2_026": {
      "type": "dialogue",
      "text": "那时候，我不该让爱理一个人待着……",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "cg": "ch2-hug-close",
      "backgroundFit": "contain",
      "next": "ch2_027"
    },
    "ch2_027": {
      "type": "dialogue",
      "text": "明明知道你心里十分不安，我却……",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "cg": "ch2-hug-close",
      "backgroundFit": "contain",
      "next": "ch2_028"
    },
    "ch2_028": {
      "type": "dialogue",
      "text": "一个劲儿地只顾说自己的事情。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "cg": "ch2-hug-close",
      "backgroundFit": "contain",
      "next": "ch2_029"
    },
    "ch2_029": {
      "type": "dialogue",
      "text": "真的非常对不起……",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "cg": "ch2-hug-close",
      "backgroundFit": "contain",
      "next": "ch2_030"
    },
    "ch2_030": {
      "type": "monologue",
      "text": "房间里安静了很久。久到基生以为，她也许永远不会回应了。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "cg": "ch2-hug-close",
      "backgroundFit": "contain",
      "next": "ch2_031"
    },
    "ch2_031": {
      "type": "dialogue",
      "text": "……基生。",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "cg": "ch2-hug-close",
      "backgroundFit": "contain",
      "next": "ch2_032"
    },
    "ch2_032": {
      "type": "dialogue",
      "text": "放开我。",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S01",
      "background": "bg-apartment-dusk",
      "cg": "ch2-hug-close",
      "backgroundFit": "contain",
      "next": "ch2_s02"
    },
    "ch2_s02": {
      "type": "monologue",
      "text": "誓约 —— “不能说”的告白",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "checkpoint": true,
      "next": "ch2_034"
    },
    "ch2_034": {
      "type": "monologue",
      "text": "爱理要求基生放开自己。基生慌忙松开双手——他误以为刚才的拥抱弄疼了她。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_035"
    },
    "ch2_035": {
      "type": "dialogue",
      "text": "诶，那个……对不起！我……！",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_036"
    },
    "ch2_036": {
      "type": "dialogue",
      "text": "难道是那时候，身上有哪里受伤了吗……！？",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_037"
    },
    "ch2_037": {
      "type": "monologue",
      "text": "爱理低着头，小声否认。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_038"
    },
    "ch2_038": {
      "type": "dialogue",
      "text": "……不，不是那样。",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "portrait": "portrait-airi",
      "next": "ch2_039"
    },
    "ch2_039": {
      "type": "monologue",
      "text": "她脸颊通红，神情慌乱。基生看到她的异常反应，又以为她正在发烧，急忙想确认她的身体状况。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_040"
    },
    "ch2_040": {
      "type": "dialogue",
      "text": "发、发烧了……！？",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_041"
    },
    "ch2_041": {
      "type": "monologue",
      "text": "爱理连忙伸手阻止他靠近。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_042"
    },
    "ch2_042": {
      "type": "dialogue",
      "text": "不、不是哦！我没事的！",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "portrait": "portrait-airi",
      "next": "ch2_043"
    },
    "ch2_043": {
      "type": "dialogue",
      "text": "我也不知道自己怎么了！？",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "portrait": "portrait-airi",
      "next": "ch2_044"
    },
    "ch2_044": {
      "type": "monologue",
      "text": "基生在她身旁坐下。短暂的沉默后，他轻轻握住爱理的双手，认真注视着她。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_045"
    },
    "ch2_045": {
      "type": "dialogue",
      "text": "爱理，我啊……",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_046"
    },
    "ch2_046": {
      "type": "dialogue",
      "text": "再也不会让你一个人待着了。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_047"
    },
    "ch2_047": {
      "type": "monologue",
      "text": "他向爱理发誓，不会再重演过去的错误。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_048"
    },
    "ch2_048": {
      "type": "dialogue",
      "text": "因为在我眼里，爱理你真的非常重要。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_049"
    },
    "ch2_049": {
      "type": "monologue",
      "text": "爱理怔怔地看着他。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_050"
    },
    "ch2_050": {
      "type": "monologue",
      "text": "基生以为她的不安，源于自己从未明确说出感情。于是，他决定不再逃避。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_051"
    },
    "ch2_051": {
      "type": "dialogue",
      "text": "所以……爱理你要是对我没有言语上的表示而感到不安的话，那么，我现在就传达给你。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_052"
    },
    "ch2_052": {
      "type": "monologue",
      "text": "基生红着脸，准备完成告白。他深吸一口气。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_053"
    },
    "ch2_053": {
      "type": "dialogue",
      "text": "我也……对爱理你……",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_054"
    },
    "ch2_054": {
      "type": "dialogue",
      "text": "最喜——",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_055"
    },
    "ch2_055": {
      "type": "monologue",
      "text": "在他说出完整的话之前，爱理突然伸手，捂住了他的嘴。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_056"
    },
    "ch2_056": {
      "type": "dialogue",
      "text": "不行！！",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "portrait": "portrait-airi",
      "next": "ch2_057"
    },
    "ch2_057": {
      "type": "monologue",
      "text": "她的反应强烈而急切，连基生也被吓住了。爱理满脸通红，眼中同时流露出渴望与恐惧。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_058"
    },
    "ch2_058": {
      "type": "dialogue",
      "text": "不能说……！",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "portrait": "portrait-airi",
      "next": "ch2_choice2"
    },
    "ch2_choice2": {
      "type": "choice",
      "text": "要怎样回应她的“不能说”？",
      "speaker": "选择",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "checkpoint": true,
      "choices": [
        {
          "text": "……好。我不说了。",
          "flag": {
            "key": "n2",
            "value": "A"
          },
          "next": "ch2_n2_a"
        },
        {
          "text": "为什么不能说？爱理。",
          "flag": {
            "key": "n2",
            "value": "B"
          },
          "next": "ch2_n2_b"
        }
      ]
    },
    "ch2_n2_a": {
      "type": "monologue",
      "text": "……",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "when": {
        "key": "n2",
        "value": "A"
      },
      "next": "ch2_061"
    },
    "ch2_061": {
      "type": "dialogue",
      "text": "……好。我不说了。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "when": {
        "key": "n2",
        "value": "A"
      },
      "next": "ch2_062"
    },
    "ch2_062": {
      "type": "monologue",
      "text": "爱理像是没料到他会这样回答，愣了愣，攥紧的手慢慢松开。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "when": {
        "key": "n2",
        "value": "A"
      },
      "next": "ch2_063"
    },
    "ch2_063": {
      "type": "dialogue",
      "text": "……嗯。",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "when": {
        "key": "n2",
        "value": "A"
      },
      "portrait": "portrait-airi",
      "next": "ch2_064"
    },
    "ch2_064": {
      "type": "monologue",
      "text": "她垂下眼，声音轻得几乎听不见。紧绷的空气，似乎松动了那么一点。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "when": {
        "key": "n2",
        "value": "A"
      },
      "next": "ch2_n2_merge"
    },
    "ch2_n2_b": {
      "type": "monologue",
      "text": "……",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "when": {
        "key": "n2",
        "value": "B"
      },
      "next": "ch2_066"
    },
    "ch2_066": {
      "type": "dialogue",
      "text": "为什么不能说？爱理。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "when": {
        "key": "n2",
        "value": "B"
      },
      "next": "ch2_067"
    },
    "ch2_067": {
      "type": "monologue",
      "text": "爱理猛地抬头，眼中的恐惧一闪而过。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "when": {
        "key": "n2",
        "value": "B"
      },
      "next": "ch2_068"
    },
    "ch2_068": {
      "type": "dialogue",
      "text": "……因为，说了的话，",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "when": {
        "key": "n2",
        "value": "B"
      },
      "portrait": "portrait-airi",
      "next": "ch2_069"
    },
    "ch2_069": {
      "type": "dialogue",
      "text": "……不，没什么。",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "when": {
        "key": "n2",
        "value": "B"
      },
      "portrait": "portrait-airi",
      "next": "ch2_070"
    },
    "ch2_070": {
      "type": "monologue",
      "text": "她说到一半，又硬生生把话吞了回去，摇了摇头。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "when": {
        "key": "n2",
        "value": "B"
      },
      "next": "ch2_n2_merge"
    },
    "ch2_n2_merge": {
      "type": "monologue",
      "text": "爱理突然站起身。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_072"
    },
    "ch2_072": {
      "type": "monologue",
      "text": "爱理突然站起身，踉跄了一下，又勉强站稳。她满脸通红，生硬地转移话题。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_073"
    },
    "ch2_073": {
      "type": "dialogue",
      "text": "啊……我……我现在已经没事啦！",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "portrait": "portrait-airi",
      "next": "ch2_074"
    },
    "ch2_074": {
      "type": "dialogue",
      "text": "所以，我稍微，去外面！呼吸一下空气！！",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "portrait": "portrait-airi",
      "next": "ch2_075"
    },
    "ch2_075": {
      "type": "monologue",
      "text": "基生对她一惊一乍的举动感到有些迷茫，迟疑地叫住她。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_076"
    },
    "ch2_076": {
      "type": "dialogue",
      "text": "诶？爱……爱理？",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_077"
    },
    "ch2_077": {
      "type": "monologue",
      "text": "爱理羞红了脸，突然指向另一个方向。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_078"
    },
    "ch2_078": {
      "type": "dialogue",
      "text": "唔～～～看那边！！",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "portrait": "portrait-airi",
      "next": "ch2_079"
    },
    "ch2_079": {
      "type": "monologue",
      "text": "基生下意识地回头。等他重新转过身时——",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_080"
    },
    "ch2_080": {
      "type": "monologue",
      "text": "房间里已经没有了她的身影。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_081"
    },
    "ch2_081": {
      "type": "dialogue",
      "text": "好快……",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_082"
    },
    "ch2_082": {
      "type": "monologue",
      "text": "爱理刚才还身体不适，现在却转眼间消失。基生怔在原地，震惊于她的恢复速度——同时也想起昨夜那毫无征兆的昏倒。这一醒一逃之间，落差大得反常。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "clues": [
        "P15",
        "P13"
      ],
      "next": "ch2_083"
    },
    "ch2_083": {
      "type": "monologue",
      "text": "就在这时，他的手机响起提示音。屏幕上，出现一封来自“百合沢 爱理”的邮件：",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_084"
    },
    "ch2_084": {
      "type": "dialogue",
      "text": "20/08/01 18:42｜发件人：百合沢 爱理｜主题：｜正文：我出去一会儿就回来，不用担心我哦！",
      "speaker": "收件时间",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_085"
    },
    "ch2_085": {
      "type": "dialogue",
      "text": "……百合沢……",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_086"
    },
    "ch2_086": {
      "type": "monologue",
      "text": "基生盯着那个名字，愣了一会儿。他这才意识到，自己其实一直只知道她叫“爱理”。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S02",
      "background": "bg-apartment-dusk",
      "next": "ch2_s03"
    },
    "ch2_s03": {
      "type": "monologue",
      "text": "江之岛 —— 上岛与牵手",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S03",
      "background": "ch2-beach",
      "checkpoint": true,
      "next": "ch2_088"
    },
    "ch2_088": {
      "type": "monologue",
      "text": "过了几天，基生与爱理一起来到江之岛。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S03",
      "background": "ch2-beach",
      "next": "ch2_089"
    },
    "ch2_089": {
      "type": "monologue",
      "text": "阳光照在海面和街道上，两人背着随身物品，沿着通往岛上的道路前进。基生抬手挡住阳光，望着远处熟悉的景色。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S03",
      "background": "ch2-beach",
      "next": "ch2_090"
    },
    "ch2_090": {
      "type": "dialogue",
      "text": "江之岛……很久没来了啊。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S03",
      "background": "ch2-beach",
      "next": "ch2_091"
    },
    "ch2_091": {
      "type": "dialogue",
      "text": "今天是个晴天，真不错呢。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S03",
      "background": "ch2-beach",
      "next": "ch2_092"
    },
    "ch2_092": {
      "type": "monologue",
      "text": "爱理站在他的身边，轻声回应。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S03",
      "background": "ch2-beach",
      "next": "ch2_093"
    },
    "ch2_093": {
      "type": "dialogue",
      "text": "嗯……是呢。",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S03",
      "background": "ch2-beach",
      "portrait": "portrait-airi",
      "next": "ch2_094"
    },
    "ch2_094": {
      "type": "monologue",
      "text": "她表面上已经恢复平静，却仍带着些许拘谨。基生看向她，突然有了一个想法——他向她伸出手。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S03",
      "background": "ch2-beach",
      "next": "ch2_hand"
    },
    "ch2_hand": {
      "type": "choice",
      "text": "他向她伸出手。",
      "speaker": "选择",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S03",
      "background": "ch2-beach",
      "checkpoint": true,
      "choices": [
        {
          "text": "牵住她的手",
          "flag": {
            "key": "CH2_HAND",
            "value": true
          },
          "next": "ch2_hand_after"
        },
        {
          "text": "稍稍迟疑",
          "flag": {
            "key": "CH2_HAND",
            "value": false
          },
          "next": "ch2_hand_hesitate"
        }
      ],
      "cg": "ch2-hand",
      "backgroundFit": "contain"
    },
    "ch2_hand_hesitate": {
      "type": "dialogue",
      "text": "……基生？她轻轻握住了那只停在半空的手。",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S03",
      "background": "ch2-beach",
      "cg": "ch2-hand",
      "backgroundFit": "contain",
      "next": "ch2_hand_after"
    },
    "ch2_hand_after": {
      "type": "monologue",
      "text": "手心的温度，随着海风传了过来。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S03",
      "background": "ch2-beach",
      "cg": "ch2-couple",
      "backgroundFit": "contain",
      "next": "ch2_098"
    },
    "ch2_098": {
      "type": "dialogue",
      "text": "走吧，爱理。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S03",
      "background": "ch2-beach",
      "next": "ch2_099"
    },
    "ch2_099": {
      "type": "monologue",
      "text": "爱理看着他的手，脸颊微微泛红。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S03",
      "background": "ch2-beach",
      "next": "ch2_100"
    },
    "ch2_100": {
      "type": "cue",
      "text": "",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S03",
      "background": "ch2-beach",
      "next": "ch2_101"
    },
    "ch2_101": {
      "type": "monologue",
      "text": "短暂停顿后，“爱理”把自己的手，交给了基生。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S03",
      "background": "ch2-beach",
      "next": "ch2_102"
    },
    "ch2_102": {
      "type": "dialogue",
      "text": "嗯！",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S03",
      "background": "ch2-beach",
      "portrait": "portrait-airi",
      "next": "ch2_103"
    },
    "ch2_103": {
      "type": "monologue",
      "text": "两人牵着手走在江之岛的桥上。爱理露出轻松的笑容，基生则不时悄悄看向她。周围依次掠过海岸、树林、鸟居和岛上的道路——形成一段安静的旅行蒙太奇。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S03",
      "background": "ch2-beach",
      "cg": "ch2-couple",
      "backgroundFit": "contain",
      "next": "ch2_g1"
    },
    "ch2_g1": {
      "type": "rpg",
      "text": "沿着海岸走到紫阳花小路入口。",
      "speaker": "旁白",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S03",
      "background": "ch2-beach",
      "task": "CH2_G1",
      "map": "ch2-island",
      "checkpoint": true,
      "follower": true,
      "timeout": 90,
      "next": "ch2_s04"
    },
    "ch2_s04": {
      "type": "monologue",
      "text": "紫阳花小路 —— 明年的约定",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-flowers",
      "checkpoint": true,
      "next": "ch2_106"
    },
    "ch2_106": {
      "type": "monologue",
      "text": "基生与爱理牵着手，沿着江之岛绿意茂盛的小路继续前行。道路两旁生长着紫阳花，眼前的景色唤起了两人过去共同来过这里的记忆。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-path-summer",
      "next": "ch2_107"
    },
    "ch2_107": {
      "type": "monologue",
      "text": "爱理停下脚步，看着周围的花木。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-path-summer",
      "next": "ch2_108"
    },
    "ch2_108": {
      "type": "dialogue",
      "text": "基生、这里……",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-path-summer",
      "portrait": "portrait-airi",
      "next": "ch2_109"
    },
    "ch2_109": {
      "type": "monologue",
      "text": "基生也认出了这个地方。他望着熟悉的小路，露出怀念的神情。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-path-summer",
      "next": "ch2_110"
    },
    "ch2_110": {
      "type": "dialogue",
      "text": "啊啊……好怀念啊。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-path-summer",
      "next": "ch2_111"
    },
    "ch2_111": {
      "type": "dialogue",
      "text": "之前是高中的时候……6 月份来的吧。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-path-summer",
      "next": "ch2_112"
    },
    "ch2_112": {
      "type": "dialogue",
      "text": "紫阳花还大片大片地开着。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-path-summer",
      "cg": "ch2-flowers",
      "backgroundFit": "contain",
      "next": "ch2_113"
    },
    "ch2_113": {
      "type": "monologue",
      "text": "爱理伸手碰了碰眼前的紫阳花。现在已经进入八月，花期即将结束，只剩下一部分花朵仍然开放。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-path-summer",
      "next": "ch2_114"
    },
    "ch2_114": {
      "type": "dialogue",
      "text": "现在已经是八月份了呢—",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-path-summer",
      "next": "ch2_115"
    },
    "ch2_115": {
      "type": "dialogue",
      "text": "啊、还有一些呢。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-path-summer",
      "next": "ch2_116"
    },
    "ch2_116": {
      "type": "monologue",
      "text": "基生脑中浮现出高中时代拍下的照片。照片里的爱理站在同一个地方，面带笑容。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-path-summer",
      "cg": "ch2-blush",
      "backgroundFit": "contain",
      "next": "ch2_117"
    },
    "ch2_117": {
      "type": "cue",
      "text": "",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-path-summer",
      "cg": "ch2-blush",
      "backgroundFit": "contain",
      "next": "ch2_g2"
    },
    "ch2_g2": {
      "type": "rpg",
      "text": "调查三处花丛，找回六月的照片。",
      "speaker": "旁白",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-path-summer",
      "task": "CH2_G2",
      "map": "ch2-flowers",
      "checkpoint": true,
      "required": [
        "memory1",
        "memory2",
        "memory3"
      ],
      "follower": true,
      "timeout": 90,
      "next": "ch2_119"
    },
    "ch2_119": {
      "type": "dialogue",
      "text": "这样啊……",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-path-summer",
      "portrait": "portrait-airi",
      "next": "ch2_120"
    },
    "ch2_120": {
      "type": "monologue",
      "text": "基生看着“爱理”沉默片刻。他没有继续沉浸在旧日回忆中，而是看向此刻站在身旁的爱理，向她提出了一个关于未来的约定。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-path-summer",
      "next": "ch2_121"
    },
    "ch2_121": {
      "type": "dialogue",
      "text": "……明年、再一起来吧。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-path-summer",
      "next": "ch2_122"
    },
    "ch2_122": {
      "type": "dialogue",
      "text": "明年 6 月份的时候。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-path-summer",
      "next": "ch2_123"
    },
    "ch2_123": {
      "type": "monologue",
      "text": "爱理微微一怔。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-path-summer",
      "next": "ch2_124"
    },
    "ch2_124": {
      "type": "dialogue",
      "text": "嗯……",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-path-summer",
      "portrait": "portrait-airi",
      "next": "ch2_125"
    },
    "ch2_125": {
      "type": "monologue",
      "text": "随后，她露出灿烂而安心的笑容。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-path-summer",
      "next": "ch2_126"
    },
    "ch2_126": {
      "type": "dialogue",
      "text": "嗯！",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-path-summer",
      "portrait": "portrait-airi",
      "next": "ch2_127"
    },
    "ch2_127": {
      "type": "dialogue",
      "text": "约好了呢！",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-path-summer",
      "portrait": "portrait-airi",
      "next": "ch2_128"
    },
    "ch2_128": {
      "type": "monologue",
      "text": "爱理走在基生身旁，两人的手再次牵在一起。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S04",
      "background": "ch2-path-summer",
      "next": "ch2_s05"
    },
    "ch2_s05": {
      "type": "monologue",
      "text": "石板路 —— 相互的告白",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S05",
      "background": "ch2-stone",
      "checkpoint": true,
      "next": "ch2_130"
    },
    "ch2_130": {
      "type": "monologue",
      "text": "两人在石板路上走了一会儿，爱理抬头看向基生，满眼爱意地说道。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S05",
      "background": "ch2-stone",
      "next": "ch2_131"
    },
    "ch2_131": {
      "type": "dialogue",
      "text": "基生、",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S05",
      "background": "ch2-stone",
      "portrait": "airi-blush",
      "next": "ch2_132"
    },
    "ch2_132": {
      "type": "dialogue",
      "text": "我呢、想和基生一直在一起。",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S05",
      "background": "ch2-stone",
      "portrait": "airi-blush",
      "next": "ch2_133"
    },
    "ch2_133": {
      "type": "monologue",
      "text": "这句话说出口后，她立刻紧张起来，试图补充说明，却因为害羞而说得断断续续。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S05",
      "background": "ch2-stone",
      "next": "ch2_134"
    },
    "ch2_134": {
      "type": "dialogue",
      "text": "是、",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S05",
      "background": "ch2-stone",
      "portrait": "airi-blush",
      "next": "ch2_135"
    },
    "ch2_135": {
      "type": "dialogue",
      "text": "这、",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S05",
      "background": "ch2-stone",
      "portrait": "airi-blush",
      "next": "ch2_136"
    },
    "ch2_136": {
      "type": "dialogue",
      "text": "……这么想的。",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S05",
      "background": "ch2-stone",
      "portrait": "airi-blush",
      "next": "ch2_137"
    },
    "ch2_137": {
      "type": "monologue",
      "text": "基生对这场突然的告白有些意外。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S05",
      "background": "ch2-stone",
      "next": "ch2_138"
    },
    "ch2_138": {
      "type": "dialogue",
      "text": "怎么了，忽然这么说……",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S05",
      "background": "ch2-stone",
      "next": "ch2_139"
    },
    "ch2_139": {
      "type": "monologue",
      "text": "爱理没有收回自己的话。她抿着唇，倔强地看着他。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S05",
      "background": "ch2-stone",
      "next": "ch2_140"
    },
    "ch2_140": {
      "type": "dialogue",
      "text": "嗯、",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S05",
      "background": "ch2-stone",
      "portrait": "airi-blush",
      "next": "ch2_141"
    },
    "ch2_141": {
      "type": "monologue",
      "text": "基生看着她，随后露出温柔的笑容，给予了明确的回应。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S05",
      "background": "ch2-stone",
      "next": "ch2_142"
    },
    "ch2_142": {
      "type": "dialogue",
      "text": "我也想和爱理一直在一起。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S05",
      "background": "ch2-stone",
      "next": "ch2_143"
    },
    "ch2_143": {
      "type": "monologue",
      "text": "听到基生的回答，爱理闭上眼睛，露出了幸福的笑容。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S05",
      "background": "ch2-stone",
      "cg": "ch2-smile",
      "backgroundFit": "contain",
      "next": "ch2_s06"
    },
    "ch2_s06": {
      "type": "monologue",
      "text": "最后一站 —— 夕阳之约",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S06",
      "background": "ch2-sunset",
      "checkpoint": true,
      "next": "ch2_145"
    },
    "ch2_145": {
      "type": "monologue",
      "text": "基生和爱理走到江之岛行程的最后一站。天色已经开始变化，基生原本准备带她回去。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S06",
      "background": "ch2-sunset",
      "next": "ch2_146"
    },
    "ch2_146": {
      "type": "dialogue",
      "text": "这里是最后一站了……差不多该回去了吧？",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S06",
      "background": "ch2-sunset",
      "next": "ch2_147"
    },
    "ch2_147": {
      "type": "monologue",
      "text": "爱理看向远处的海面，轻轻应了一声。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S06",
      "background": "ch2-sunset",
      "next": "ch2_148"
    },
    "ch2_148": {
      "type": "dialogue",
      "text": "啊……",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S06",
      "background": "ch2-sunset",
      "portrait": "portrait-airi",
      "next": "ch2_149"
    },
    "ch2_149": {
      "type": "dialogue",
      "text": "……嗯、",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S06",
      "background": "ch2-sunset",
      "portrait": "portrait-airi",
      "next": "ch2_150"
    },
    "ch2_150": {
      "type": "monologue",
      "text": "基生忽然想起昨天查到的资料。从这里能够看到很漂亮的夕阳。既然今天是约会，他不想就这样结束，于是叫住了她。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S06",
      "background": "ch2-sunset",
      "next": "ch2_151"
    },
    "ch2_151": {
      "type": "dialogue",
      "text": "……对了！",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S06",
      "background": "ch2-sunset",
      "next": "ch2_152"
    },
    "ch2_152": {
      "type": "dialogue",
      "text": "……这里、可以看到很漂亮的夕阳呢。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S06",
      "background": "ch2-sunset",
      "next": "ch2_153"
    },
    "ch2_153": {
      "type": "dialogue",
      "text": "我昨天、调查过了。怎么说、也是约会……",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S06",
      "background": "ch2-sunset",
      "next": "ch2_154"
    },
    "ch2_154": {
      "type": "dialogue",
      "text": "所以……",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S06",
      "background": "ch2-sunset",
      "next": "ch2_155"
    },
    "ch2_155": {
      "type": "monologue",
      "text": "基生有些不好意思地摸着脸，试探着向她发出邀请。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S06",
      "background": "ch2-sunset",
      "next": "ch2_156"
    },
    "ch2_156": {
      "type": "dialogue",
      "text": "还有一些时间……要一起看夕阳吗？",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S06",
      "background": "ch2-sunset",
      "next": "ch2_157"
    },
    "ch2_157": {
      "type": "monologue",
      "text": "爱理睁大眼睛，随即露出笑容。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S06",
      "background": "ch2-sunset",
      "next": "ch2_158"
    },
    "ch2_158": {
      "type": "dialogue",
      "text": "！",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S06",
      "background": "ch2-sunset",
      "portrait": "portrait-airi",
      "next": "ch2_159"
    },
    "ch2_159": {
      "type": "dialogue",
      "text": "嗯！我想看！",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S06",
      "background": "ch2-sunset",
      "portrait": "portrait-airi",
      "next": "ch2_160"
    },
    "ch2_160": {
      "type": "monologue",
      "text": "基生决定和她留在海边，等待太阳落下。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S06",
      "background": "ch2-sunset",
      "next": "ch2_161"
    },
    "ch2_161": {
      "type": "dialogue",
      "text": "……嗯、那么我们在这里等一会儿吧。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S06",
      "background": "ch2-sunset",
      "next": "ch2_162"
    },
    "ch2_162": {
      "type": "dialogue",
      "text": "嗯！",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S06",
      "background": "ch2-sunset",
      "portrait": "portrait-airi",
      "next": "ch2_s07"
    },
    "ch2_s07": {
      "type": "monologue",
      "text": "售货机前 —— 十年与“幸福”",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-sunset",
      "checkpoint": true,
      "next": "ch2_164"
    },
    "ch2_164": {
      "type": "monologue",
      "text": "等待期间，基生想去附近买些饮料。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-sunset",
      "next": "ch2_165"
    },
    "ch2_165": {
      "type": "dialogue",
      "text": "那么、我——",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-sunset",
      "next": "ch2_166"
    },
    "ch2_166": {
      "type": "dialogue",
      "text": "去买点喝的吧。爱理你想喝什么呢？",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-sunset",
      "next": "ch2_167"
    },
    "ch2_167": {
      "type": "monologue",
      "text": "爱理摇头拒绝。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-sunset",
      "next": "ch2_168"
    },
    "ch2_168": {
      "type": "dialogue",
      "text": "啊，我就不用了！",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-sunset",
      "portrait": "portrait-airi",
      "next": "ch2_choice3"
    },
    "ch2_choice3": {
      "type": "choice",
      "text": "买水，还是留下？",
      "speaker": "选择",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-sunset",
      "checkpoint": true,
      "choices": [
        {
          "text": "还是去买点喝的吧——稍等我一下。",
          "flag": {
            "key": "n3",
            "value": "buy"
          },
          "next": "ch2_buy"
        },
        {
          "text": "……算了，反正也不是很渴。就这样陪着她吧。",
          "flag": {
            "key": "n3",
            "value": "stay"
          },
          "next": "ch2_s07-e"
        }
      ]
    },
    "ch2_buy": {
      "type": "dialogue",
      "text": "知道了。那么稍等我一下。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-sunset",
      "next": "ch2_171"
    },
    "ch2_171": {
      "type": "dialogue",
      "text": "知道了。那么稍等我一下。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-sunset",
      "next": "ch2_172"
    },
    "ch2_172": {
      "type": "monologue",
      "text": "她随即站起来，表示想和基生一起走。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-sunset",
      "next": "ch2_173"
    },
    "ch2_173": {
      "type": "dialogue",
      "text": "我也想一起去！",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-sunset",
      "portrait": "portrait-airi",
      "next": "ch2_174"
    },
    "ch2_174": {
      "type": "monologue",
      "text": "通往商店还要爬很长的楼梯。基生不想让她跟着受累，便让她留在原地等自己。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-sunset",
      "next": "ch2_175"
    },
    "ch2_175": {
      "type": "dialogue",
      "text": "不用了不用了。因为还要爬楼梯，很累的。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-sunset",
      "next": "ch2_176"
    },
    "ch2_176": {
      "type": "monologue",
      "text": "爱理迟疑了一下，最后还是答应了。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-sunset",
      "next": "ch2_177"
    },
    "ch2_177": {
      "type": "dialogue",
      "text": "是、是吗？那……嗯、我等你回来哦。",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-sunset",
      "portrait": "portrait-airi",
      "next": "ch2_178"
    },
    "ch2_178": {
      "type": "dialogue",
      "text": "嗯。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-sunset",
      "next": "ch2_179"
    },
    "ch2_179": {
      "type": "monologue",
      "text": "临走前，基生看着她身后的海面，还是有些不放心。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-sunset",
      "next": "ch2_180"
    },
    "ch2_180": {
      "type": "dialogue",
      "text": "……不会掉进海里去的吧？",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-sunset",
      "next": "ch2_181"
    },
    "ch2_181": {
      "type": "monologue",
      "text": "爱理马上大声反驳。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-sunset",
      "next": "ch2_182"
    },
    "ch2_182": {
      "type": "dialogue",
      "text": "才不会啦！！",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-sunset",
      "portrait": "portrait-airi",
      "next": "ch2_183"
    },
    "ch2_183": {
      "type": "monologue",
      "text": "她站在原地向他挥手。基生也抬手回应，然后独自沿楼梯向上走。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-sunset",
      "next": "ch2_g3"
    },
    "ch2_g3": {
      "type": "rpg",
      "text": "沿石阶找到售货机，买一瓶冰水。",
      "speaker": "旁白",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "task": "CH2_G3",
      "map": "ch2-stairs",
      "checkpoint": true,
      "required": [
        "water"
      ],
      "timeout": 90,
      "next": "ch2_185"
    },
    "ch2_185": {
      "type": "monologue",
      "text": "经过很长一段台阶后，基生终于抵达自动售货机。按下饮料按钮时，腰腿传来的酸痛让他不得不弯下身体休息。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_186"
    },
    "ch2_186": {
      "type": "cue",
      "text": "",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_187"
    },
    "ch2_187": {
      "type": "cue",
      "text": "",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_188"
    },
    "ch2_188": {
      "type": "monologue",
      "text": "十年前来这里时，他从没觉得这些楼梯有多难爬。他的想法似乎没有发生多少变化，身体却已经留下了岁月的痕迹。他花了 160（日）元在售货机里买了一瓶冰镇矿泉水，拧开盖子喝了起来。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_189"
    },
    "ch2_189": {
      "type": "cue",
      "text": "",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_190"
    },
    "ch2_190": {
      "type": "cue",
      "text": "",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_191"
    },
    "ch2_191": {
      "type": "monologue",
      "text": "他想起了爱理不久前对他说过的话。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_192"
    },
    "ch2_192": {
      "type": "dialogue",
      "text": "我想和基生一直在一起。",
      "speaker": "“爱理”：",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "portrait": "portrait-airi",
      "next": "ch2_193"
    },
    "ch2_193": {
      "type": "monologue",
      "text": "江之岛的景色与十年前几乎没有区别。看着相同的海岸和天空，他偶尔还会产生自己仍是高中生的错觉。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_194"
    },
    "ch2_194": {
      "type": "cue",
      "text": "",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_195"
    },
    "ch2_195": {
      "type": "cue",
      "text": "",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_196"
    },
    "ch2_196": {
      "type": "monologue",
      "text": "在那种错觉里，爱理陪在他身边，爸爸妈妈也仍然在家里等他。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_197"
    },
    "ch2_197": {
      "type": "cue",
      "text": "",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_198"
    },
    "ch2_198": {
      "type": "monologue",
      "text": "但他知道，那段生活已经结束。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_199"
    },
    "ch2_199": {
      "type": "cue",
      "text": "",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_200"
    },
    "ch2_200": {
      "type": "cue",
      "text": "",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_201"
    },
    "ch2_201": {
      "type": "monologue",
      "text": "基生的脑海里，浮现出这些日子里一直陪伴在他身边的“爱理”的身影。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_202"
    },
    "ch2_202": {
      "type": "cue",
      "text": "",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_203"
    },
    "ch2_203": {
      "type": "cue",
      "text": "",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_204"
    },
    "ch2_204": {
      "type": "cue",
      "text": "",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_205"
    },
    "ch2_205": {
      "type": "cue",
      "text": "",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_206"
    },
    "ch2_206": {
      "type": "cue",
      "text": "",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_207"
    },
    "ch2_207": {
      "type": "monologue",
      "text": "他握着刚买到的饮料，第一次清楚地意识到自己此刻的感受。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_208"
    },
    "ch2_208": {
      "type": "cue",
      "text": "",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_209"
    },
    "ch2_209": {
      "type": "cue",
      "text": "",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_210"
    },
    "ch2_210": {
      "type": "monologue",
      "text": "休息过后，他准备返回海边。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_211"
    },
    "ch2_211": {
      "type": "cue",
      "text": "",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_212"
    },
    "ch2_212": {
      "type": "monologue",
      "text": "路过冰淇淋店时，他停了下来。他想起爱理在便利店里看到冰淇淋时兴奋的模样，于是走到柜台前。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-vending",
      "next": "ch2_g4"
    },
    "ch2_g4": {
      "type": "rpg",
      "text": "在柜台挑选冰淇淋，带回给爱理。",
      "speaker": "旁白",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-shop",
      "task": "CH2_G4",
      "map": "ch2-shop",
      "checkpoint": true,
      "required": [
        "ice"
      ],
      "timeout": 90,
      "next": "ch2_214"
    },
    "ch2_214": {
      "type": "dialogue",
      "text": "不好意思，请给我来一个。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-shop",
      "next": "ch2_215"
    },
    "ch2_215": {
      "type": "monologue",
      "text": "店员把冰淇淋递给他。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-shop",
      "next": "ch2_216"
    },
    "ch2_216": {
      "type": "dialogue",
      "text": "请拿好，欢迎下次光临—",
      "speaker": "店员",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07",
      "background": "ch2-shop",
      "cg": "ch2-ice",
      "backgroundFit": "contain",
      "next": "ch2_s08"
    },
    "ch2_s07-e": {
      "type": "monologue",
      "text": "中间结局 —— Just two of us",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "checkpoint": true,
      "next": "ch2_218"
    },
    "ch2_218": {
      "type": "monologue",
      "text": "基生看了看远处那条通往商店街的长楼梯，又看了看身边的爱理——她正望着海面，侧脸被落日前的暖光描出一圈细细的边。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "next": "ch2_219"
    },
    "ch2_219": {
      "type": "cue",
      "text": "",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "next": "ch2_220"
    },
    "ch2_220": {
      "type": "cue",
      "text": "",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "next": "ch2_221"
    },
    "ch2_221": {
      "type": "dialogue",
      "text": "……不去买了。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "next": "ch2_222"
    },
    "ch2_222": {
      "type": "dialogue",
      "text": "就这样，陪你等夕阳吧。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "next": "ch2_223"
    },
    "ch2_223": {
      "type": "monologue",
      "text": "爱理惊讶地转过头来。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "next": "ch2_224"
    },
    "ch2_224": {
      "type": "dialogue",
      "text": "诶……？不去了吗？",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "portrait": "portrait-airi",
      "next": "ch2_225"
    },
    "ch2_225": {
      "type": "dialogue",
      "text": "嗯。人这么多，万一我走开的时候，你被奇怪的人搭话了怎么办。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "next": "ch2_226"
    },
    "ch2_226": {
      "type": "dialogue",
      "text": "才、才不会有人搭话啦！",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "portrait": "portrait-airi",
      "next": "ch2_227"
    },
    "ch2_227": {
      "type": "monologue",
      "text": "嘴上这么说，她却往基生那边挪了半步，悄悄坐近了一点。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "next": "ch2_228"
    },
    "ch2_228": {
      "type": "dialogue",
      "text": "……不过，这样也好。",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "portrait": "portrait-airi",
      "next": "ch2_229"
    },
    "ch2_229": {
      "type": "dialogue",
      "text": "基生在的话，就够了。",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "portrait": "portrait-airi",
      "next": "ch2_230"
    },
    "ch2_230": {
      "type": "monologue",
      "text": "那天傍晚，两个人谁都没有再说什么重要的话。聊的全是无关紧要的小事——十年前来江之岛时吃过的、硬得像纸板的可丽饼，紫阳花到底算不算花，海鸥是不是真的认得回家的路。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "next": "ch2_231"
    },
    "ch2_231": {
      "type": "dialogue",
      "text": "那时候的可丽饼，明明那么难吃……",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "portrait": "portrait-airi",
      "next": "ch2_232"
    },
    "ch2_232": {
      "type": "dialogue",
      "text": "你还记到现在啊。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "next": "ch2_233"
    },
    "ch2_233": {
      "type": "dialogue",
      "text": "因为是和基生一起吃的嘛。",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "portrait": "portrait-airi",
      "next": "ch2_234"
    },
    "ch2_234": {
      "type": "monologue",
      "text": "太阳一点一点沉向海平线。就在它只剩最后一道金边的时候，爱理忽然开口。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "next": "ch2_235"
    },
    "ch2_235": {
      "type": "dialogue",
      "text": "基生。",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "portrait": "portrait-airi",
      "next": "ch2_236"
    },
    "ch2_236": {
      "type": "dialogue",
      "text": "谢谢你，今天陪我来。",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "portrait": "portrait-airi",
      "next": "ch2_237"
    },
    "ch2_237": {
      "type": "dialogue",
      "text": "这样的傍晚……要是能一直、一直继续下去，就好了。",
      "speaker": "“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "portrait": "portrait-airi",
      "next": "ch2_238"
    },
    "ch2_238": {
      "type": "dialogue",
      "text": "会一直的。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "next": "ch2_239"
    },
    "ch2_239": {
      "type": "dialogue",
      "text": "明年、后年……我们都再来。",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "next": "ch2_240"
    },
    "ch2_240": {
      "type": "monologue",
      "text": "爱理没有回答，只是笑了一下，把头轻轻靠在了基生的肩上。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "next": "ch2_241"
    },
    "ch2_241": {
      "type": "monologue",
      "text": "暮色温柔地漫上来，把海、把岛、把两个人一起包裹进去。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "next": "ch2_242"
    },
    "ch2_242": {
      "type": "monologue",
      "text": "没有长楼梯，没有售货机，也没有任何身影会在他回来时变成别的模样的疑问。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "next": "ch2_243"
    },
    "ch2_243": {
      "type": "monologue",
      "text": "这个傍晚，只有两个人——Just two of us。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S07-E",
      "background": "ch2-sunset",
      "next": "ending_just2"
    },
    "ch2_s08": {
      "type": "monologue",
      "text": "归来 —— 成年的“爱理”",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S08",
      "background": "ch2-sunset",
      "checkpoint": true,
      "next": "ch2_g5"
    },
    "ch2_g5": {
      "type": "rpg",
      "text": "回到海边，寻找等候的身影。",
      "speaker": "旁白",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S08",
      "background": "ch2-sunset",
      "task": "CH2_G5",
      "map": "ch2-return",
      "checkpoint": true,
      "required": [
        "figure"
      ],
      "timeout": 30,
      "next": "ch2_246"
    },
    "ch2_246": {
      "type": "monologue",
      "text": "基生带着冰淇淋回到海边。隔着一段距离，他看见了爱理的身影……",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S08",
      "background": "ch2-sunset",
      "next": "ch2_247"
    },
    "ch2_247": {
      "type": "monologue",
      "text": "夕阳下，出现了一名留着长发、拥有成年女性身形的人。她与爱理极为相似，却又不是他刚才看到的模样。纤细的身姿在夕阳的映照下那样动人，长发在风中飘舞着，仿佛晚风吹过的细柳；而那双动人的酒红色双眸，和那张似曾相识却又十分成熟的面庞——",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S08",
      "background": "ch2-sunset",
      "next": "ch2_248"
    },
    "ch2_248": {
      "type": "monologue",
      "text": "基生握着冰淇淋，僵在原地。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S08",
      "background": "ch2-sunset",
      "cg": "ch2-adult",
      "backgroundFit": "contain",
      "next": "ch2_249"
    },
    "ch2_249": {
      "type": "dialogue",
      "text": "爱理……？",
      "speaker": "基生",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S08",
      "background": "ch2-sunset",
      "cg": "ch2-adult",
      "backgroundFit": "contain",
      "next": "ch2_250"
    },
    "ch2_250": {
      "type": "monologue",
      "text": "长发女性同样注视着基生。她的神情显得惊讶，似乎正在辨认他的身份。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S08",
      "background": "ch2-sunset",
      "cg": "ch2-adult",
      "backgroundFit": "contain",
      "next": "ch2_251"
    },
    "ch2_251": {
      "type": "dialogue",
      "text": "那……个……",
      "speaker": "成年“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S08",
      "background": "ch2-sunset",
      "cg": "ch2-adult",
      "backgroundFit": "contain",
      "next": "ch2_252"
    },
    "ch2_252": {
      "type": "dialogue",
      "text": "难道你是——",
      "speaker": "成年“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S08",
      "background": "ch2-sunset",
      "cg": "ch2-adult",
      "backgroundFit": "contain",
      "next": "ch2_253"
    },
    "ch2_253": {
      "type": "monologue",
      "text": "她迟疑着，叫出了他的名字。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S08",
      "background": "ch2-sunset",
      "cg": "ch2-adult",
      "backgroundFit": "contain",
      "next": "ch2_254"
    },
    "ch2_254": {
      "type": "dialogue",
      "text": "基生……",
      "speaker": "成年“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S08",
      "background": "ch2-sunset",
      "cg": "ch2-adult",
      "backgroundFit": "contain",
      "next": "ch2_255"
    },
    "ch2_255": {
      "type": "dialogue",
      "text": "君……？",
      "speaker": "成年“爱理”",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S08",
      "background": "ch2-sunset",
      "cg": "ch2-adult",
      "backgroundFit": "contain",
      "next": "ch2_256"
    },
    "ch2_256": {
      "type": "monologue",
      "text": "基生无法回答。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S08",
      "background": "ch2-sunset",
      "cg": "ch2-adult",
      "backgroundFit": "contain",
      "next": "ch2_257"
    },
    "ch2_257": {
      "type": "monologue",
      "text": "周围的海面、夕阳和游客都没有改变。只有刚才还在等他买水的“爱理”，毫无征兆地，变成了十年后应有的成年模样。",
      "speaker": "",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "S08",
      "background": "ch2-sunset",
      "cg": "ch2-adult",
      "backgroundFit": "contain",
      "next": "ch3_s01"
    },
    "ending_just2": {
      "type": "end",
      "chapter": "chapter2",
      "chapterTitle": "第二章 · 约定与夕阳",
      "scene": "END",
      "title": "Just two of us",
      "text": "这一段故事，留在了这里。",
      "background": "ch2-sunset",
      "ending": "ENDING_JUST2",
      "achievement": "Just two of us",
      "checkpoint": true
    }
  }
};
